version: '3.8'

services:  
  mongo:
    volumes:
      - movie_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
  moviehub-api:
    build: ./backend
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo
  moviehub-ui:
    depends_on:
      - moviehub-api
    build: ./frontend
    ports:
      - 5173:5173
volumes:
  movie_db: